### PR TITLE
Case insensitive filtering of words

### PR DESCRIPTION
**Pull request by kashifeqbal**
clean function modified, use string search function based on word regex
to use case insensitive. and replace is also case insensitive

### CODE REVIEW

**Comment by jwils0n** [comment]
Could you use an alternative to preg_quote? Seeing how it doesn't exist in Javascript.

**Comment by kashifeqbal** [comment]
I have added the function preg_quote.

**Comment by kashifeqbal** [comment]
Could you please update this on NPM

**Comment by jwils0n** [comment]
I'm sorry, I don't like this implementation. It is slow and unnecessary as long as the dictionary is populated with lower case words.

**Pull request closed without merging**
